Graph loader clean up, optimization, and threading
waynebhayes/SANA pull request #53
Opened 2018-12-19 03:25 UTC by beneaththeglamour

Graph loading is now all through references (before only serialized loading was by reference)
Graphs can now load concurrently on different threads
Graphs can now serialize concurrently on different threads while annealing
Some clean up

2018-12-20 20:48 UTC, waynebhayes requested changes
Please do a rebase and resubmit; the USE_CACHED_FILES code needs to remain, and it was pulled in after your most recent rebase.

2018-12-21 00:35 UTC, beneaththeglamour commented
USE_CACHED_FILES code is still there.
I just reorganized it and removed the places where it was doing nothing.

2018-12-24 17:56 UTC, beneaththeglamour commented
#if SERIAL was removed and merged into #if USE_CACHED_FILES

Should I undo that? Otherwise, it's fine as is.

2018-12-25 12:09 UTC, waynebhayes approved these changes

2018-12-25 12:09 UTC, merged