Modified SANA core frequency scoring
waynebhayes/SANA pull request #60
Opened 2019-01-31 22:23 UTC by rasulsafa

2019-01-31 22:53 UTC, rasulsafa reviewed
Tweaked core frequency measurements

2019-01-31 22:58 UTC, waynebhayes commented on src/methods/SANA.cpp
> +#define PRINT_CORES 1
Leave PRINT_CORES 0 by default, and add code instead to put these scores (unweighted only for now) to a ".scores" file.

2019-01-31 23:06 UTC, waynebhayes commented on src/methods/SANA.cpp
> +    if(wasBadMove && !makeChange)
I think the only thing we want to find out is which hole is the better place to be; set a variable equal to either source or newTarget; and then have the code inside the #if CORES only once, using that variable.

2019-01-31 23:12 UTC, waynebhayes requested changes

2019-01-31 23:12 UTC, waynebhayes commented on src/methods/SANA.cpp
>      if (makeChange) {
Consider the case that it's a bad move but we're going to accept it anyway. Then the above (wasBadMove && !makeChange) is false and doesn't get executed. Then here, where the bad move is accepted, you're incrementing the bad guy's core count.

2019-02-06 15:24 UTC, waynebhayes commented on src/methods/SANA.cpp
> +        uint betterHole = wasBadMove ? source : newTargetIndex;
Good idea, but I think also if you create a "worseHole" variable it'll be useful below. See later comment.

2019-02-06 15:25 UTC, waynebhayes commented on src/methods/SANA.cpp
> +        if(wasBadMove)
If you create the "worseHole" above, then you can get rid of this if-else statement and just use "bestHole" and "worseHole".

2019-02-07 05:06 UTC, waynebhayes approved these changes

2019-02-07 05:06 UTC, merged