[WIP] Handle self-loops(needs to be tested)
waynebhayes/SANA pull request #61
Opened 2019-02-01 18:41 UTC by idetatsu

I am still running the regression test to make sure there is no unwanted changes, but here's the code that we discussed last week.

It allows both graphs g1 and g2 to have self-loops and (hopefully) is able to align them as well. We'll be able to test if that's the case by the test suite that I am working on right now.

2019-02-03 00:14 UTC, waynebhayes commented on src/Graph.cpp
> +    if(std::find(neighbors.begin(), neighbors.end(), source) != neighbors.end()) {
This seems terribly expensive. Why not just check the single bit that's along the diagonal of the adjacency matrix?

Note that the method you have here *will* be necessary if SPARSE is true; but if SPARSE is false then just perform the O(1) operation of looking at the diagonal of the adjacency matrix.

2019-02-03 00:15 UTC, waynebhayes commented on src/methods/SANA.cpp
> +    if(G1->hasSelfLoop(source)) {
Again even calling this function may add uncessary expense. If SPARSE is false, just check the adjacencry matrix inline right here. Perform the function call only of SPARSE is true and it's necessary to perform the O(degree) search.

2019-02-03 00:15 UTC, waynebhayes commented on src/methods/SANA.cpp
> +    if(G1->hasSelfLoop(source1)) {
Same here.

2019-02-03 00:15 UTC, waynebhayes commented on src/methods/SANA.cpp
> +    if(G1->hasSelfLoop(source2)) {
And here.

2019-02-03 00:16 UTC, waynebhayes requested changes
I think your code is *correct* but may be unnecessarily expensive. See comments for details.

Especially in the IncChangeOp() dfunctions, these get called millions of times per second. They need to be lightning fast.

2019-02-03 00:30 UTC, idetatsu commented on src/Graph.cpp
> +    if(std::find(neighbors.begin(), neighbors.end(), source) != neighbors.end()) {
I had just forgotten I could use adjacency matrix when I implemented it. I'll fix this.

2019-02-03 02:01 UTC, waynebhayes commented
Ok cool

Sent from my iPhone

> On Feb 1, 2019, at 10:41, Tatsuro Ide <notifications@github.com> wrote:
> 
> I am still running the regression test to make sure there is no unwanted changes, but here's the code that we discussed last week.
> 
> It allows both graphs g1 and g2 to have self-loops and (hopefully) is able to align them as well. We'll be able to test if that's the case by the test suite that I am working on right now.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/waynebhayes/SANA/pull/61
> 
> Commit Summary
> 
> Handle self-loops(needs to be tested)
> File Changes
> 
> M src/Graph.cpp (38)
> M src/Graph.hpp (2)
> M src/methods/SANA.cpp (39)
> Patch Links:
> 
> https://github.com/waynebhayes/SANA/pull/61.patch
> https://github.com/waynebhayes/SANA/pull/61.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-02-11 18:55 UTC, waynebhayes commented
Any more news on this?

2019-02-23 17:13 UTC, waynebhayes commented
It's been almost a month.  Can we get this in soon?  I also haven't seen
you in meetings for awhile.  If you want to continue in the group, get this
done this week.

--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.


On Sat, Feb 2, 2019 at 6:01 PM Wayne Hayes <whayes@uci.edu> wrote:

> Ok cool
>
> Sent from my iPhone
>
> On Feb 1, 2019, at 10:41, Tatsuro Ide <notifications@github.com> wrote:
>
> I am still running the regression test to make sure there is no unwanted
> changes, but here's the code that we discussed last week.
>
> It allows both graphs g1 and g2 to have self-loops and (hopefully) is able
> to align them as well. We'll be able to test if that's the case by the test
> suite that I am working on right now.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/waynebhayes/SANA/pull/61
> Commit Summary
>
>    - Handle self-loops(needs to be tested)
>
> File Changes
>
>    - *M* src/Graph.cpp
>    <https://github.com/waynebhayes/SANA/pull/61/files#diff-0> (38)
>    - *M* src/Graph.hpp
>    <https://github.com/waynebhayes/SANA/pull/61/files#diff-1> (2)
>    - *M* src/methods/SANA.cpp
>    <https://github.com/waynebhayes/SANA/pull/61/files#diff-2> (39)
>
> Patch Links:
>
>    - https://github.com/waynebhayes/SANA/pull/61.patch
>    - https://github.com/waynebhayes/SANA/pull/61.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/waynebhayes/SANA/pull/61>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATUkjDen86nF8oKKHPrEBsmxJJMGEVIpks5vJIpAgaJpZM4ae3WJ>
> .
>
>

2019-03-07 09:49 UTC, idetatsu commented
@waynebhayes I'm sorry I took so long to finish this. I have made changes regarding what you mentioned earlier. Please check it out.

2019-03-07 18:02 UTC, waynebhayes approved these changes

2019-03-07 18:02 UTC, merged